version: '3'

services:
  hr-database:
    image: mysql:8.0.17
    command: '--default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1'
    ports:
    - 3306:3306
    environment:
      MYSQL_USER: 'user'
      MYSQL_DATABASE: 'hr'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'